# -*- coding: utf-8 -*-
"""precificacao_imoveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12c2Mbpylg1CRmxHB07wsB6sjcDr9qLoZ
"""

import pandas as pd

dados = pd.read_json('/content/dados_hospedagem.json')
dados.head()

dados = pd.json_normalize(dados['info_moveis'])
dados



colunas = list(dados.columns)
colunas

dados = dados.explode(colunas[3:])
dados

dados.reset_index(inplace=True, drop=True)
dados.head()

dados.info()

import numpy as np

dados['max_hospedes'] = dados['max_hospedes'].astype(np.int64)

dados.info()

col_numericas = ['quantidade_banheiros', 'quantidade_quartos', 'quantidade_camas']

dados[col_numericas] = dados[col_numericas].astype(np.int64)
dados.info()

dados['avaliacao_geral'] = dados['avaliacao_geral'].astype(np.float64)
dados.info()

dados['preco'] = dados['preco'].apply(lambda x: x.replace('$', '').replace(',','').strip())

dados['preco'] = dados['preco'].astype(np.float64)
dados.info()

dados[['taxa_deposito', 'taxa_limpeza']] = dados[['taxa_deposito', 'taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',','').strip())

dados[['taxa_deposito', 'taxa_limpeza']] = dados[['taxa_deposito', 'taxa_limpeza']].astype(np.float64)
dados.info()

dados['descricao_local'] = dados['descricao_local'].str.lower()

dados.head()

dados['descricao_local'][3169]

dados['descricao_local'] = dados['descricao_local'].str.replace('[^a-zA-Z0-9\-\']', ' ',regex=True)

dados['descricao_local'] = dados['descricao_local'].str.replace('(?<!\w)-(?!\w)', ' ',regex=True)

dados['descricao_local'] = dados['descricao_local'].str.split()

dados.head()

dados['comodidades'] = dados['comodidades'].str.replace('\{|}|\"', ' ', regex=True)

dados['comodidades'] = dados['comodidades'].str.split(',')
dados.head()

dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.lower()

dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']', ' ',regex=True)

dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)', ' ',regex=True)

dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.split()

dados['descricao_local'].head()

"""DATATIME

"""

dados_moveis = pd.read_json('/content/moveis_disponiveis.json')

dados_moveis.head()

dados_moveis.info()

dados_moveis['data'] = pd.to_datetime(dados_moveis['data'])

dados_moveis.info()

dados_moveis.head()

dados_moveis['data'].dt.strftime('%Y-%m')

subset = dados_moveis.groupby(dados_moveis['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
subset

